version: '3.3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx_noc1
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            - ./nginx/www:/var/www/
            - ./nginx/logs:/var/log/nginx/
            - ./nginx/html:/usr/share/nginx/html/
        links:
            - php
    
    mysql:
        image: mariadb
        ports:
            - "3306:3306"
        container_name: mysql_noc1
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_noc1
        ports:
            - "8090:80"
        links:
            - mysql:db

    php:
        build: ./php
        container_name: php-fpm_noc1
        volumes:
            - ./nginx/www:/var/www
        links:
            - mysql

    memcached:
        image: memcached:${MEMCACHED_VERSION}
        container_name: memcached_noc1
        ports:
            - 11212:11211
